---
title: "exploratory_data_ana"
author: "athibault92"
date: "2020-07-02"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(readr)
library(tidyverse)
library(sf)
library(leaflet)
library(ggthemr)
library(tidymodels)
ggthemr('dust')
```


## Introduction

Exploration des variables du jeu de données GDGT

```{r warning=FALSE, message=FALSE}
data_gdgt <- readr::read_delim("./data/Dearing_Crampton-Flood-etal_2019.tab", delim = "\t", skip = 40)

skimr::skim(data_gdgt)
```

Aucunes données manquantes

## Carte des localisation

```{r}
sf_data <- data_gdgt %>%
  sf::st_as_sf(coords = c("Longitude", "Latitude"), crs = 4326)

leaflet(sf_data) %>%
  addCircleMarkers() %>%
  addTiles()

```

## Analyse des données d'interet

Garde MAT, MBT, IR6me, et les GDGT

```{r}
data_model <- data_gdgt %>%
  janitor::clean_names() %>%
  dplyr::select(mat_c, mbt5me, ir6me, starts_with("br"))
```

```{r}
data_model %>%
  ggplot(aes(x=mbt5me, y=mat_c)) +
  geom_point(aes(color = ir6me)) + 
  stat_smooth(method = "lm") +
  scale_color_viridis_c()
```

```{r}
data_model %>%
  ggplot(aes(x=factor(mbt5me), y=mat_c)) +
  geom_boxplot()
```

## Quels sont les GDGT qui ont un lien avec la MAT ?

```{r}
data_gdgt <- data_model %>%
  dplyr::select(starts_with("br"), "mat_c")

bs_gdgt <- bootstraps(data_gdgt, times = 1000, apparent = TRUE)

boot_models <- bs_gdgt %>%
  mutate(
    reg = map(splits, ~lm(mat_c ~ ., data = .)),
    coef_info = map(reg, tidy)
  )
boot_coefs <- boot_models %>%
  unnest(coef_info)

# int_pctl(boot_models, coef_info)

boot_coefs %>%
  filter(term != "(Intercept)") %>%
  mutate(term = fct_inorder(term)) %>%
  ggplot(aes(estimate, fill = term)) +
  geom_vline(
    xintercept = 0, color = "gray50",
    alpha = 0.6, lty = 2, size = 1.5
  ) +
  geom_histogram(alpha = 0.8, bins = 25, show.legend = FALSE) +
  facet_wrap(~term, scales = "free") + 
  scale_fill_viridis_d()

```



